import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {createBankHandler} from '../netlify/functions/_shared/handler.mjs';
import {cleanBank} from '../netlify/functions/_shared/validation.mjs';
import defaults from '../netlify/functions/_shared/default-bank.json' with {type:'json'};
const clone=v=>JSON.parse(JSON.stringify(v));
function fixture(){
  let user=null,record=null,etag=0,conflict=false;
  const store={async get(){return record&&clone(record);},async getWithMetadata(){return record&&{data:clone(record),etag:String(etag)};},async setJSON(key,data,conditions){if(conflict||(conditions.onlyIfNew&&record)||(conditions.onlyIfMatch&&conditions.onlyIfMatch!==String(etag)))return {modified:false};record=clone(data);etag++;return {modified:true,etag:String(etag)};}};
  const handler=createBankHandler({getUser:async()=>user,getStore:()=>store,validate:cleanBank,defaults,uuid:()=>`revision-${etag+1}`,now:()=>new Date(0).toISOString()});
  const request=(worlds=clone(defaults),baseRevision='initial-v1',extra={})=>new Request('https://classroom.netlify.app/api/question-bank',{method:'PUT',headers:{origin:'https://classroom.netlify.app','content-type':'application/json',...extra},body:JSON.stringify({worlds,baseRevision})});
  return {handler,request,read:()=>handler(new Request('https://classroom.netlify.app/api/question-bank')),teacher:()=>{user={id:'teacher-id',roles:['teacher']};},setUser:u=>{user=u;},race:()=>{conflict=true;}};
}
test('students read all 240 defaults without login, with no cache',async()=>{const f=fixture(),r=await f.read(),data=await r.json();assert.equal(r.status,200);assert.equal(data.worlds.flatMap(w=>w.levels.flatMap(l=>l.questions)).length,240);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(data.revision,'initial-v1');});
test('anonymous writes rejected',async()=>{const f=fixture();assert.equal((await f.handler(f.request())).status,401);});
test('ordinary users and user-controlled role claims cannot publish',async()=>{const f=fixture();f.setUser({id:'student',roles:['student'],userMetadata:{roles:['teacher']}});assert.equal((await f.handler(f.request())).status,403);});
test('teacher cross-site writes rejected',async()=>{const f=fixture();f.teacher();assert.equal((await f.handler(f.request(defaults,'initial-v1',{origin:'https://other.example'}))).status,403);});
test('teacher edits immediately visible to a fresh anonymous reader',async()=>{const f=fixture();f.teacher();const bank=clone(defaults);bank[0].levels[0].questions[0].question='ข้อสอบใหม่ที่ครูแก้บนเว็บ';bank[0].levels[0].questions[0].correct=3;const response=await f.handler(f.request(bank));assert.equal(response.status,200);const {revision}=await response.json();f.setUser(null);const data=await(await f.read()).json();assert.equal(data.revision,revision);assert.equal(data.worlds[0].levels[0].questions[0].question,'ข้อสอบใหม่ที่ครูแก้บนเว็บ');assert.equal(data.worlds[0].levels[0].questions[0].correct,3);assert(!JSON.stringify(data).includes('teacher-id'));});
test('old editor revision cannot overwrite new publication',async()=>{const f=fixture();f.teacher();assert.equal((await f.handler(f.request())).status,200);assert.equal((await f.handler(f.request())).status,409);});
test('atomic write detects concurrent publication',async()=>{const f=fixture();f.teacher();f.race();assert.equal((await f.handler(f.request())).status,409);});
test('server rejects duplicates independently of browser validation',async()=>{const f=fixture();f.teacher();const bank=clone(defaults);bank[0].levels[1].questions[0]=clone(bank[0].levels[0].questions[0]);const r=await f.handler(f.request(bank));assert.equal(r.status,400);assert.match((await r.json()).error,/ซ้ำ/);});
test('question text must be unique even with different passages and punctuation',async()=>{const f=fixture();f.teacher();const bank=clone(defaults);bank[1].levels[0].questions[0].question=' '+bank[0].levels[0].questions[0].question+'? ';const r=await f.handler(f.request(bank));assert.equal(r.status,400);assert.match((await r.json()).error,/ซ้ำ/);const texts=defaults.flatMap(w=>w.levels.flatMap(l=>l.questions.map(q=>q.question)));assert.equal(new Set(texts).size,240);});
test('malformed answers and missing stages cannot be published',async()=>{const f=fixture();f.teacher();const bank=clone(defaults);bank[0].levels[0].questions[0].correct=9;assert.equal((await f.handler(f.request(bank))).status,400);bank[0].levels.pop();assert.equal((await f.handler(f.request(bank))).status,400);});
test('storage failure reports error rather than silently serving stale defaults',async()=>{const h=createBankHandler({getUser:async()=>null,getStore:()=>{throw Error('offline');},defaults,validate:cleanBank});assert.equal((await h(new Request('https://classroom.netlify.app/api/question-bank'))).status,503);});
test('online game source compiles and never loads a local teacher override',async()=>{const html=await readFile('public/index.html','utf8');const scripts=[...html.matchAll(/<script type="application\/x-ar-game"[^>]*>([\s\S]*?)<\/script>/g)];assert.equal(scripts.length,8);for(const [i,m]of scripts.entries())new vm.Script(m[1],{filename:`game-${i}`});assert(!html.includes('localStorage.getItem(AR_BANK_KEY)'));assert(html.includes('const AR_DEFAULT_BANK=window.AROnline.bank.worlds'));assert(html.includes('await window.AROnline.requireTeacher()'));assert(html.includes('window.AROnline.publish(next,AR_BANK_REVISION)'));assert(!html.includes('getUserMedia'));});
